### ISSUE TITLE
CI Test Suite always red: docs/test/ping.test.ts can't resolve .nuxt/tsconfig.json

### ISSUE THREAD

**Issue by pmcp** [pmcp/nuxt-crouton#880]
## 👤 For humans

The repo's **"Test Suite" CI check fails on every PR** — not because of the PR, but because the docs site's one vitest file (`docs/test/ping.test.ts`) can't start. It tries to load `docs/.nuxt/tsconfig.json`, which only exists after `nuxt prepare` has run — and the Test Suite job doesn't prepare the docs app before running vitest. Result: a permanently-red (but non-blocking) check that trains everyone to ignore CI red. Worth fixing so green means green.

## 🤖 For agents — archaeology

- **First-bad commit:** `c4591d2` *"feat(docs): add /ping health endpoint with test"* — added `docs/test/ping.test.ts`, the first (and only) vitest file in the docs app. Before it, the docs app contributed nothing to the root `Test Suite` run, so the missing-`.nuxt` condition never surfaced.
- **Symptom:** `TSConfckParseError: failed to resolve "extends":"./.nuxt/tsconfig.json" in docs/tsconfig.json` → `Cannot find module './.nuxt/tsconfig.json'` (vite:esbuild loading tsconfig for the test file). Reproduces in CI's root `pnpm test`; the file passes locally only when `docs/.nuxt` exists from a prior `nuxt prepare`/`postinstall`.
- **Not a code regression in the test itself** — it's a missing-prepare ordering issue in how the aggregate Test Suite runs the docs package.

## 🤖 Fix options (pick on triage)
1. Ensure `nuxt prepare` runs for `docs` before the root `Test Suite` job (CI step, or a `pretest` in `docs/package.json`).
2. Or make `docs/tsconfig.json`'s `extends` resilient when `.nuxt` is absent (generate a stub, or guard the test's vite tsconfig resolution).
3. Or scope the root `test` script so an unprepared app can't break the aggregate run.

## 🧪 How to test
On a PR, the **Test Suite** check is green (no `TSConfckParseError`); `pnpm test` from a clean checkout (no prior `nuxt prepare`) passes the docs package.

---
*Found while merging #877 (the Test Suite check was red there for this reason, non-blocking). Non-required check, so it doesn't block merges today — but it makes CI red the normal state, which is the real cost.*
