### ISSUE TITLE
nuxt 4.4.x not a clean bump: i18n `locales` config type tightened (blocks getting Nuxt current)

### ISSUE THREAD

**Issue by pmcp** [pmcp/nuxt-crouton#241]
Part of #233. Discovered while attempting the "safe" Nuxt bump (4.3.1 → 4.4.8).

## 👤 For humans
Bumping Nuxt one minor (4.3 → 4.4) **breaks our typecheck** — not at runtime, but the TypeScript gate fails across apps. The newer Nuxt tightened how it types the list of languages (i18n locales), and the way our shared packages build that list no longer satisfies the stricter type. So Nuxt can't move to 4.4 until we adjust that one pattern in the packages. This is exactly the kind of thing the typecheck gate is meant to catch before it reaches an app.

## 🤖 For agents
**Trigger:** `@nuxt/schema@4.4.8` (pulled by `nuxt@4.4.8`) narrows the `i18n.locales` config type to `string[] | LocaleObject<LiteralCode>[]`, where `code` must be the literal locale union (e.g. `"nl"`, `"en" | "fr" | "nl"`), not `string`.

**Failure (on nuxt 4.4.8, clean install, `pnpm -r --filter './apps/*' typecheck`):**
```
packages/crouton-pages/nuxt.config.ts(141,5): error TS2322:
  Type '{ code: string; name: string; file: string; }[]' is not assignable to
  type 'string[] | LocaleObject<"nl">[] | undefined'.
```
Same error in `crouton-core`, `crouton-i18n`, `crouton-auth`, `crouton-admin`, `crouton-sales`, `crouton-pages` nuxt.configs. fanfare + velo both fail; the only diff vs green is the nuxt version.

**Root pattern** (e.g. `crouton-pages/nuxt.config.ts:141`):
```ts
i18n: {
  locales: croutonLocales.map(l => ({ code: l.code, name: l.name, file: l.file })),
  langDir: './locales'
}
```
`.map(...)` widens `code` to `string`; the new type wants the literal-coded `LocaleObject`.

**Fix options (needs packages/ gate approval):**
- Annotate the mapped array as `LocaleObject[]` (import the type from `@nuxtjs/i18n`), or
- `satisfies LocaleObject[]`, or
- type `croutonLocales`' `code` as the literal union at the source (`getCroutonLocales`).
Pick one and apply consistently across all affected package nuxt.configs. Re-validate with a **clean** `pnpm -r --filter './apps/*' typecheck` (note: a stale node_modules can throw a spurious `Cannot find module '@vue/compiler-sfc'` — `rm -rf node_modules && pnpm install` if so).

**Until fixed:** the catalog stays at `nuxt: ^4.3.1` (do not bump).

## 🧪 How to test
- Bump `nuxt` to `^4.4.8` in the `catalog:` block, `pnpm install`.
- `pnpm -r --filter './apps/*' typecheck` → green (no TS2322 on i18n locales).
- Run the `e2e-smoke` (minimal + with-pages) to confirm boot/CRUD still work on Nuxt 4.4.

**Comment by pmcp** [comment]
## Update from the nuxt 4.4.8 attempt (PR #248): nuxt 4.4 needs TWO package-side fixes, not one

Holding nuxt at `^4.3.1` for now (dependency-sweep policy: don't force a red framework bump). PR #248 ships the **vue 3.5.38** half (#242) only; this issue stays open with both blockers below.

### Blocker A — i18n locales (this issue's original scope; solved approach)
`@nuxt/schema@4.4.8` narrows `i18n.locales` to literal-coded `LocaleObject[]`. Fix that validated green (apps typecheck @ 4.4.8): `import type { LocaleObject } from '@nuxtjs/i18n'` + `as LocaleObject[]` on the `.map(...)` in the 6 layer configs (`crouton-core`, `-i18n`, `-auth`, `-admin`, `-pages`, `-sales`). Prototyped on the branch, then reverted with the hold — re-apply when nuxt moves.

### Blocker B — NEW: `defineNuxtConfig` not callable in the E2E fixture-typecheck gate
The e2e gate (`pnpm install --ignore-scripts` → `pnpm --filter e2e-fixture-* typecheck`) fails on nuxt 4.4.8 for **every** layer/package `nuxt.config.ts` (including ones this PR never touched, e.g. `crouton-assets`):
```
nuxt.config.ts: error TS2349: This expression is not callable.
  Type 'DefineNuxtConfig' has no call signatures.
```
Investigation (faithful `--ignore-scripts` repro, all confirmed locally):
- **Trigger = nuxt 4.4.8.** Green on 4.3.1; the only diff is the nuxt version. The apps gate ("Lint & Type Check") stays green — only the fixture gate (#197) is red.
- **Chain:** `nuxt/config` → `@nuxt/schema@4.4.8` declares `interface DefineNuxtConfig extends DefineConfig`, where `DefineConfig` (from **c12**) is a bare function *type alias* `(input) => InputConfig`. An interface extending a bare-function alias loses the call signature in the fixture's non-prepared typecheck program.
- **NOT a c12 version mismatch:** the required `c12@3.3.4` is installed and has the *identical* `DefineConfig` shape (the stray `c12@1.11.2` is just `changelogen` dev noise).
- **Explicit `import { defineNuxtConfig } from 'nuxt/config'` does NOT fix it** (proven — error persists). A full `nuxt prepare` fixes the fixture's *own* config but **not** the workspace package configs (they're never prepared as apps).

Likely a Nuxt 4.4 typegen/type-resolution issue. Candidate directions for the next attempt (none yet validated):
1. Check for an upstream Nuxt fix / newer 4.4.x patch (and re-check `@vue/language-core` — see the related `vue-router/volar/sfc-route-blocks` warning, relevant to #237).
2. Exclude `**/nuxt.config.ts` from the fixture typecheck gate — weakens #197, but configs aren't that gate's intended target.
3. A prepare-based workflow change that reaches layer configs.
4. Wait for the supported range to settle (overlaps with #237).

Reproduce: `rm -rf node_modules && pnpm install --frozen-lockfile --ignore-scripts` (with nuxt bumped to ^4.4.8) → build a fixture's deps → `crouton-generate config --force` → `pnpm --filter e2e-fixture-minimal typecheck`.

---
_Generated by [Claude Code](https://claude.ai/code)_
